agilefant/webapp/src/main/java/fi/hut/soberit/agilefant/model/Setting.java
package fi.hut.soberit.agilefant.model;

import java.util.Collection;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.Type;

/**
 * Hibernate entity bean representing a Setting.
 * <p>
 * Settings are global options that can be used for instance to enable or disable
 * features in Agilefant. For example the whole hour reporting functionality can be
 * enabled or disabled using the Settings system.
 * </p>
 * <p>
 * Each setting includes a name, a description and a String-type value.
 * </p>
 * @warning The settings page is currently hard-coded. If you want to use the name or description
 *          fields of settings, you need to write the functionality to settings.jsp. 
 * 
 */
@BatchSize(size=20)
@Entity
@Table(name = "settings")
@XmlAccessorType( XmlAccessType.NONE )
public class Setting {

    private int id;
    
    private String name;
    
    private String description;
    
    private String value;
    
    /**
     * Get the id of this object.
     */
    // tag this field as the id
    @Id
    // generate automatically
    @GeneratedValue(strategy = GenerationType.AUTO)
    public int getId() {
        return id;
    }
    
    /**
     * Set the id of this object.
     * <p>
     * You shouldn't normally call this.
     */
    public void setId(int id) {
        this.id = id;
    }

    @Type(type = "escaped_truncated_varchar")
    @Column(unique = true, nullable = false)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Type(type = "escaped_truncated_varchar")
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Type(type = "escaped_truncated_varchar")
    public String getValue() {
        return value;
    }
    
    public void setValue(String value) {
        this.value = value; 
    }
    
    @Transient
    public Backlog getParent() {
        return null;
    }

    @Transient
    public Collection<Backlog> getChildren() {
        return null;
    }
    
    @Transient
    public boolean hasChildren() {
        return false;
    }
}

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/checkStoryMove.jsp
<%@include file="/WEB-INF/jsp/inc/_taglibs.jsp" %>

<c:if test="${fn:length(messages) > 0 || parentStoryConflict}">
<div class="messageContainer">

<img alt="" src="static/img/attention.png" style="float:right;"/>

<h2>Can't move story to <span style="color: #666;"><c:out value="${backlog.name}" /></span></h2>

<script type="text/javascript">
<!--
var messageUrls = {
    "MOVE_TO_ITERATION_HAS_CHILDREN": "static/html/storyconstraints/moveToIterationHasChildren.html",
    "CHILD_IN_WRONG_BRANCH":          "static/html/storyconstraints/childInWrongBranch.html",
    "PARENT_DEEPER_IN_HIERARCHY":     "static/html/storyconstraints/parentDeeperInHierarchy.html",
    "PARENT_IN_WRONG_BRANCH":         "static/html/storyconstraints/childInWrongBranch.html"
};
var suggestionUrls = {
    "moveStoryOnly":           "ajax/suggestion_moveStoryOnly.action",
    "moveStoryAndChildren":    "ajax/suggestion_moveStoryAndChildren.action"
};

var openElement = function openElement(selector, type) {
  var elem = $(selector);
  $('#please-select-an-option').hide();
  // Hide all other previously shown options
  $('.closable').not(elem).not(':hidden').hide('blind');

  // Load the option contents
  if (elem.is(':hidden')) {
    elem.show('blind');
  }
};

var toggleElement = function toggleElement(selector, type) {
  $(selector).toggle('blind');
};


//-->
</script>

<table>
  <tr>
    <td><strong>Reason:</strong></td>
    <td>
      <ul>
      <c:forEach items="${messages}" var="msg">
        <li>
        <c:choose>
          <c:when test="${msg.target != null}">
            <aef:text name="${msg.messageName}" />
            <a href="#" class="quickHelpLink superScript" title="What's this?" onclick="HelpUtils.openHelpPopup(this,'<aef:text name="${msg.messageName}" />',messageUrls['${msg.message}']); return false;">[?]</a>:
            <span style="color: #999;"><c:out value="${msg.target.name}"/></span>
            in
            <span style="color: #999">${msg.target.backlog.name}</span>  
          </c:when>
          <c:otherwise>
            <aef:text name="${msg.messageName}" />
            <a href="#" class="quickHelpLink superScript" title="What's this?" onclick="HelpUtils.openHelpPopup(this,'<aef:text name="${msg.messageName}" />',messageUrls['${msg.message}']); return false;">[?]</a>         
          </c:otherwise>
        </c:choose>
        
        </li>
        
      </c:forEach>
      </ul>
    </td>
  </tr>
</table>

<h3>Current story hierarchy</h3>
<div class="hierarchyContainer">
  <div class="storyTreeContainer">
    <div class="tree">
      <ul>
        <ai:storyTreeNode moveStoryNode="${data}" />
      </ul>
    </div>
  </div>
</div>
<div class="possibleAction">

  <h3>Possible actions</h3>
  
  
  
  <style>
  .action-message {
    border: 1px dashed #A6C9E2;
    margin: 0.5em 0;
    padding: 0.3em;
  }
  .action-message h4 {
    margin-top: 0.5em;
    margin-bottom: 0.3em;
  }
  .closable {
    display: none;
  }
  </style>
  
  <ul style="list-style-type: none;">
    
    <%--
    <c:if test="${parentStoryConflict == true}">
      <li>
        <input type="checkbox" value="" name="moveParentsToProduct" onchange="toggleElement('#suggestion_moveParentsToProduct','moveParentsToProduct');return false;"/>
        Move story's parents to product
      </li>
      <li id="suggestion_moveParentsToProduct" style="display: none;">
        <div class="action-message">
          <div style="text-align: center;"><img src="static/img/pleasewait.gif" alt="Please wait..." style="vertical-align: middle;" /> <span style="color: #666;">Loading suggestion..</span></div>
        </div>
      </li>
    </c:if>
     --%>
    
    <li>
      <input type="radio" value="moveTargetStoryOnly" name="selectedAction" onchange="openElement('#suggestion_storyOnlyMessage','moveStoryOnly');return false;"/> 
      <c:choose>
      <c:when test="${empty story.children}">
        Move the story      
      </c:when>
      <c:otherwise>
        Move the story and leave the children behind
      </c:otherwise>
      </c:choose>
    </li>
      
    <li id="suggestion_storyOnlyMessage" class="closable">
      <div class="action-message">
        <%@ include file="/WEB-INF/jsp/forms/moveOptions/moveOption_moveStoryOnly.jsp" %>
        <%--<div style="text-align: center;"><img src="static/img/pleasewait.gif" alt="Please wait..." style="vertical-align: middle;" /> <span style="color: #666;">Loading suggestion..</span></div> --%>
      </div>
    </li>
    

    <c:if test="${!aef:isIteration(backlog) && !empty story.children}">
      <li>
        <input type="radio" value="moveTargetAndItsChildren" name="selectedAction" onchange="openElement('#suggestion_storyAndChildrenMessage','moveStoryAndChildren');return false;"/>
        Move the story and all of its children
      </li>
      <li id="suggestion_storyAndChildrenMessage" class="closable">
        <div class="action-message">
          <%@ include file="/WEB-INF/jsp/forms/moveOptions/moveOption_moveStoryAndChildren.jsp" %>
        </div>
      </li>
    </c:if>
  
  </ul>
  
  </div>
  
  <div id="please-select-an-option" class="warning-note" style="display:none;">
    Please select an option from the list!
  </div>

</div>
</c:if>

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/deleteIterationForm.jsp
<%@ include file="../inc/_taglibs.jsp"%>
<form>
	<div class="deleteForm">
	<div><img src="static/img/question.png" alt="Are you sure?" style="float: left;" />
	<div style="margin-left: 90px">
		<p>Are you sure you want to delete this iteration and all of its contents?</p>
		<p style="color: #ff0000">This operation can not be reversed!</p>
		<div class="confirmation">
		<input type="checkbox" name="confirmationString" value="yes" /> Yes, delete the iteration and all of its contents.
		</div>
	 </div></div>
	</div>
</form>

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/deleteProductForm.jsp
<%@ include file="../inc/_taglibs.jsp"%>
<form>
  <div class="deleteForm">
  <div><img src="static/img/question.png" alt="Are you sure?" style="float: left;" />
  <div style="margin-left: 90px">
    <p>Are you sure you want to delete this product and all of its contents?</p>
    <p style="color: #ff0000">This operation can not be reversed!</p>
    <div class="confirmation">
    <input type="checkbox" name="confirmationString" value="yes" /> Yes, delete the product and all of its contents.
    </div>
   </div></div>
  </div>
</form>

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/deleteProjectForm.jsp
<%@ include file="../inc/_taglibs.jsp"%>
<form>
  <div class="deleteForm">
  <div><img src="static/img/question.png" alt="Are you sure?" style="float: left;" />
  <div style="margin-left: 90px">
    <p>Are you sure you want to delete this project and all of its contents?</p>
    <p style="color: #ff0000">This operation can not be reversed!</p>
    <div class="confirmation">
    <input type="checkbox" name="confirmationString" value="yes" /> Yes, delete the project and all of its contents.
    </div>
   </div></div>
  </div>
</form>

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/deleteStoryForm.jsp
<%@ include file="../inc/_taglibs.jsp"%>
  <div><img src="static/img/question.png" alt="Are you sure?" style="float: left;" />
  <div style="margin-left: 90px">
<c:choose>
	<c:when test="${empty story.hourEntries && empty story.tasks && empty story.children}">
		Delete story?
	</c:when>
	<c:otherwise>
		<form>
		  <div class="deleteForm">
        <c:if test="${!empty story.children}">
          <p>This story has children.</p>
          <ul>
            <li>
              <input type="radio" name="childHandlingChoice" value="MOVE" onchange="$('#deleteChildren').hide();" checked="checked" />
              <c:choose>
              <c:when test="${story.parent != null}">
                Move the children to the story's parent: <span style="color: #666;">${story.parent.name}</span>
              </c:when>
              <c:otherwise>
                Move the children to be root stories
              </c:otherwise>
              </c:choose>
            </li>
            <li>
              <input type="radio" name="childHandlingChoice" value="DELETE" onchange="$('#deleteChildren').show('blind');"/>
              Delete all the children
            </li>
            <li id="deleteChildren" style="display: none; border: 1px dashed #A6C9E2; padding: 0.5em;">
              <h4>These stories will be deleted!</h4>
              
              <p style="font-weight: normal;"><strong>Note!</strong> The children may contain tasks and hour entries which will be deleted!</p>
              
              <div class="hierarchyContainer">
                <div class="storyTreeContainer">
                  <div class="tree">
                    <ul>
                      <ai:storyTreeNode_forStory node="${story}" />
                    </ul>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </c:if>
      
				<c:if test="${!empty story.tasks}">
					<p>This story contains tasks.</p>
					<ul>
						<c:choose>
							<c:when test="${aef:isIteration(story.backlog)}">
								<li>
									<input type="radio" name="taskHandlingChoice" value="MOVE" checked="checked" />
									Move the tasks to the iteration '${story.backlog.name}'.
								</li>
								<li>
									<input type="radio" name="taskHandlingChoice" value="DELETE" />
									Delete the tasks.
								</li>
								<li class="taskHourEntryHandling" style="display: none">
									<p>Some tasks might contain spent effort entries.</p>
									<ul>
										<li>
											<input type="radio" name="taskHourEntryHandlingChoice" value="MOVE" />
											Move the spent effort entries to the iteration '${story.backlog.name}'.
										</li>
										<li>
											<input type="radio" name="taskHourEntryHandlingChoice" value="DELETE" />
											Delete the spent effort entries.
										</li>
									</ul>
								</li>
							</c:when>
							<c:otherwise>
								<li style="color: #ff0000">
									<input type="hidden" name="taskHandlingChoice" value="DELETE" checked="checked"/>
									The tasks will be permanently deleted.
								</li>
								<li class="taskHourEntryHandling">
									<p>Some tasks might contain spent effort entries.</p>
									<ul>
										<li>
											<input type="radio" name="taskHourEntryHandlingChoice" value="MOVE" checked="checked" />
											Move the spent effort entries to the <c:if test="${aef:isProject(story.backlog)}">project</c:if><c:if test="${aef:isProduct(story.backlog)}">product</c:if> '${story.backlog.name}'.
										</li>
										<li>
											<input type="radio" name="taskHourEntryHandlingChoice" value="DELETE" />
											Delete the spent effort entries.
										</li>
									</ul>
								</li>
							</c:otherwise>
						</c:choose>
					</ul>
				</c:if>
				<c:if test="${!empty story.hourEntries}">
					<p>This story contains spent effort entries.</p>
					<ul>
						<li>
							<input type="radio" name="storyHourEntryHandlingChoice" value="MOVE" checked="checked" />
							Move the spent effort entries to the <c:if test="${aef:isProject(story.backlog)}">project</c:if><c:if test="${aef:isProduct(story.backlog)}">product</c:if> '${story.backlog.name}'.
						</li>
						<li>
							<input type="radio" name="storyHourEntryHandlingChoice" value="DELETE" />
							Delete the spent effort entries.
						</li>
					</ul>
				</c:if>
			</div>
		</form>
	</c:otherwise>
</c:choose>
</div>
</div>

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/deleteTaskForm.jsp
<%@ include file="../inc/_taglibs.jsp"%>
<div><img src="static/img/question.png" alt="Are you sure?"
	style="float: left;" />
<div style="margin-left: 90px"><c:choose>
	<c:when test="${empty task.hourEntries}">
		Delete task?
	</c:when>
	<c:otherwise>
		<form>
		<div class="deleteForm">
		<p>This task contains spent effort entries.</p>
		<ul>
			<li><input type="radio" name="hourEntryHandlingChoice"
				value="MOVE" checked="checked" /> Move the spent effort entries to
			the <c:choose>
				<c:when test="${task.story == null}">iteration '${task.iteration.name}'</c:when>
				<c:otherwise>story '${task.story.name}'</c:otherwise>
			</c:choose></li>
			<li><input type="radio" name="hourEntryHandlingChoice"
				value="DELETE" /> Delete the spent effort entries.</li>
		</ul>
		</div>
		</form>
	</c:otherwise>
</c:choose></div>
</div>

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/deleteTeamForm.jsp
<%@ include file="../inc/_taglibs.jsp"%>
<div><img src="static/img/question.png" alt="Are you sure?"
	style="float: left;" />
<div style="margin-left: 90px">
	Are you sure you want to delete this Team?</div>
</div>

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/shareIterationForm.jsp
<%@ include file="../inc/_taglibs.jsp"%>
<form>
    <div class="shareIterationForm">
      <div><img src="static/img/agilefant-logo-80px.png" alt="Share iteration" style="float: left;" />
        <div style="margin-left: 90px">
          <p>Send the following URL to grant the recipients read-only access to this iteration:</p>

          <%--
            If you are using proxy, getRequestURL() will have serverName/serverPort pointing to the proxied host (eg. localhost).
            To fix this, add the following settings to your Tomcat server.xml file's Connector:
            proxyName="YOURHOSTNAME" (eg. "cloud.agilefant.org")
            proxyPort="YOURHOSTPORT" (eg. "80")
          --%>
          <%
          	String url = request.getRequestURL().toString();
          	url = url.substring(0, url.indexOf("WEB-INF"));
          	url = url.concat("token/"); 
          %>
          
          <p><b><%=url%>${readonlyToken}</b></p>
          <p>&nbsp;</p>
          <p style="font-size: 8pt">Note: If the server name/port are wrong in the above url, contact the person who is responsible for your Agilefant installation. He needs to set the proxyName and proxyPort parameters to Tomcat's server.xml. </p>
          <%--
          <p><b>${readonlyToken}</b></p>
          <p>Usage:<br>[the URL of your Agilefant instance]/ROIteration.action?readonlyToken=[token]</p>
          <p>Example:<br>http://cloud.agilefant.org/community/ROIteration.action?readonlyToken=${readonlyToken}</p>
           --%>
        
          <%--
          <script>
	          var text_input = document.getElementById ('tokenUrl');
	          text_input.focus ();
	          text_input.select ();
          </script>
          --%>
        </div>
      </div>
    </div>
</form>

agilefant/webapp/src/main/webapp/WEB-INF/jsp/forms/unshareIterationForm.jsp
<%@ include file="../inc/_taglibs.jsp"%>
<form class="unshareIterationForm">
<div><img src="static/img/question.png" alt="Confirm Read Only Unshare?"
	style="float: left;" />
<div style="margin-left: 90px">
	<p>Are you sure you want remove the read only share link for this iteration?</p>
	<p>If you decide to share this iteration again, you will need to redistribute a new link.</p>
	</div>
</div>
</form>